// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBChJGZ_0h_LSNztEO9xIVsS56FP4T8fXI',
    appId: '1:668021446319:web:b0bfa8247fd9996bf6a65a',
    messagingSenderId: '668021446319',
    projectId: 'nerd-studio-c4bf2',
    authDomain: 'nerd-studio-c4bf2.firebaseapp.com',
    storageBucket: 'nerd-studio-c4bf2.appspot.com',
    measurementId: 'G-9HNNH36TT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoHbQCK5BWpwJQ2IJzLI33f8iMqb1hrXg',
    appId: '1:668021446319:android:67c20e583c0e01d3f6a65a',
    messagingSenderId: '668021446319',
    projectId: 'nerd-studio-c4bf2',
    storageBucket: 'nerd-studio-c4bf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUoPlTNwoSL69GB8pDeHUp8oUPa-CpFEE',
    appId: '1:668021446319:ios:e4d9287d2c23e968f6a65a',
    messagingSenderId: '668021446319',
    projectId: 'nerd-studio-c4bf2',
    storageBucket: 'nerd-studio-c4bf2.appspot.com',
    iosBundleId: 'com.example.nerdStudio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUoPlTNwoSL69GB8pDeHUp8oUPa-CpFEE',
    appId: '1:668021446319:ios:e4d9287d2c23e968f6a65a',
    messagingSenderId: '668021446319',
    projectId: 'nerd-studio-c4bf2',
    storageBucket: 'nerd-studio-c4bf2.appspot.com',
    iosBundleId: 'com.example.nerdStudio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBChJGZ_0h_LSNztEO9xIVsS56FP4T8fXI',
    appId: '1:668021446319:web:ac06899286035903f6a65a',
    messagingSenderId: '668021446319',
    projectId: 'nerd-studio-c4bf2',
    authDomain: 'nerd-studio-c4bf2.firebaseapp.com',
    storageBucket: 'nerd-studio-c4bf2.appspot.com',
    measurementId: 'G-F9EQXWBN3F',
  );
}
